Repository OctoFarm/OctoFarm, pull requests merged in 2021-05, with the labels that each got.

#517 Duplicate username regression
  server_src/models/User.js
  test/domain/user-schema.test.js
Labels: bug, effort-5, fixed

#520 Fixed #495 - return function if air_gapped detected
  client_src/js/settings.js
  views/assets/js/settings.min.js
Labels: effort-5, fixed

#522 Bugfix/498 fix package version
  CHANGELOG.md
  app-env.js
  package-lock.json
  package.json
  server_src/app.constants.js
  server_src/routes/databaseIssue.js
  server_src/routes/index.js
  server_src/runners/__mocks__/githubClient.js
  server_src/runners/softwareUpdateChecker.js
  server_src/services/system-information.service.js
  test/api/server-check.test.js
Labels: bug, chore, effort-5

#519 Bugfix/518 printers no show
  client_src/js/printerManagementRunner.js
  server_src/lib/dataFunctions/printerClean.js
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
Labels: effort-5, fixed

#533 Hotfix/update button notification
  CHANGELOG.md
  client_src/js/serverAliveCheck.js
  views/assets/js/serverAliveCheck.min.js
  views/assets/js/serverAliveCheck.min.js.map
Labels: bug

#556 Chore/update pkg
  package-lock.json
  package.json
Labels: chore

#560 Squashed vue work
  client_web/.eslintrc.js
  client_web/package-lock.json
  client_web/package.json
  client_web/src/components/PrinterManager/Management.vue
  client_web/src/components/PrinterManager/Management/OctoFarm/BulkOctoFarmActions.vue
  client_web/src/components/PrinterManager/Management/OctoFarm/ConnectionLog.vue
  client_web/src/components/PrinterManager/Management/OctoFarm/PrinterTable.vue
  client_web/src/components/PrinterManager/Management/OctoPrintActions/BulkOctoPrintActions.vue
  client_web/src/components/PrinterManager/Management/UniversalPrinterActions/BulkPrinterActions.vue
  client_web/src/components/PrinterManager/PrinterTable.vue
  client_web/src/components/Toolbar/UserNotifications.vue
  client_web/src/views/admin/PrinterManager.vue
Labels: chore

#561 366 v2 history clean
  .gitignore
  server_2x/src/api/legacy_lib/dataFunctions/historyClean.js
  server_2x/src/printers/entities/mocks/printer-history-entity.mock.ts
  server_2x/src/printers/interfaces/history-cache.interface.ts
  server_2x/src/printers/models/apex-key-value.model.ts
  server_2x/src/printers/models/history-cache-item.model.ts
  server_2x/src/printers/models/history-file.model.ts
  server_2x/src/printers/models/history-statistics.model.ts
  server_2x/src/printers/models/job-analysis.model.ts
  server_2x/src/printers/models/spool.model.ts
  server_2x/src/printers/printers.constants.ts
  server_2x/src/printers/printers.module.ts
  server_2x/src/printers/services/history-cache.service.ts
  server_2x/src/printers/services/history.cache.spec.ts
  server_2x/src/printers/services/history.cache.ts
  server_2x/src/printers/services/history.service.ts
  server_2x/src/printers/services/mock-data/Histories.json
  server_2x/src/printers/services/mock-data/HistoryStatisticsReference.json
  server_2x/src/printers/services/mock-data/HistoryStatisticsReferenceUninitiated.json
  server_2x/src/printers/utils/array.util.ts
  server_2x/src/printers/utils/html.util.ts
  server_2x/src/printers/utils/number.util.ts
  server_2x/src/printers/utils/print-cost.util.ts
  server_2x/src/printers/utils/property.util.ts
  server_2x/src/printers/utils/time.util.ts
  server_2x/src/settings/services/server-settings-cache.service.ts
  server_2x/src/settings/settings.module.ts
  server_2x/src/utils/types/fixed.type.ts
  server_2x/tsconfig.json
Labels: effort-5

#580 Upgrade mongoose, fix circular import, fix ensureIndex warning
  CHANGELOG.md
  app.js
  package-lock.json
  package.json
  server_src/runners/filamentManagerPlugin.js
  server_src/runners/history.js
Labels: effort-5

#568 Bugfix/567 heatmap race condition
  CHANGELOG.md
  app-env.js
  server_src/lib/dataFunctions/historyClean.js
  server_src/lib/dataFunctions/printerClean.js
  server_src/lib/tests/printer-clean.test.js
  server_src/routes/index.js
  server_src/runners/state.js
  server_src/services/__mocks__/farm-statistics.service.js
  server_src/services/farm-statistics.service.js
  server_src/services/printer.service.js
  server_src/settings/serverSettings.js
  server_src/utils/env.utils.js
Labels: effort-5

#570 Bugfix/546 node version abort page
  CHANGELOG.md
  app-core.js
  app-env.js
  app-fallbacks.js
  app-test.js
  app.js
  server_src/lib/dataFunctions/printerClean.js
  server_src/lib/tests/history.service.test.js
  server_src/routes/databaseIssue.js
  server_src/routes/index.js
  server_src/routes/nodeVersionIssue.js
  server_src/routes/serverChecks.js
  server_src/routes/settings.js
  server_src/runners/state.js
  test/api/server-check.test.js
  test/api/settings-check.test.js
  test/application/server-commands.test.js
  test/domain-shared/download-from-octoprint-util.test.js
  views/nodeVersionIssue.ejs
Labels: fixed

#426 FileClean refactor
  CHANGELOG.md
  server_src/lib/dataFunctions/fileClean.js
  server_src/lib/dataFunctions/settingsClean.js
  server_src/lib/tests/file-clean.test.js
Labels: chore, effort-5, fixed

#545 Feature/printer settings dialog improvements
  .prettierignore
  .prettierrc.js
  CHANGELOG.md
  babel.config.js
  client_src/js/lib/functions/ui.js
  client_src/js/lib/modules/printerSettings.js
  client_src/js/lib/octofarm.js
  client_src/js/lib/octofarm_client.js
  client_src/js/printerManagementRunner.js
  ecosystem.config.js
  package.json
  server_src/config/__mocks__/auth.js
  server_src/lib/dataFunctions/filamentClean.js
  server_src/lib/dataFunctions/printerClean.js
  server_src/lib/tests/mock-data/Histories.json
  server_src/routes/SSE-dashboard.js
  server_src/routes/SSE-monitoring.js
  server_src/routes/SSE-printersInfo.js
  server_src/routes/index.js
  server_src/routes/printers.js
  server_src/runners/state.js
  test/api/amialive.test.js
  test/api/printers-settings.test.js
  test/domain-shared/mock-data/package.json
  views/assets/css/vendor/balloon.css.map
  views/assets/css/vendor/bootstrap-v4.css.map
  views/assets/css/vendor/bootstrap.css.map
  views/assets/css/vendor/font-awesome.css.map
  views/assets/css/vendor/jplist.css.map
  views/assets/css/vendor/noty.css.map
  views/assets/css/vendor/slate.css.map
  views/assets/js/cameraViewRunner.min.js
  views/assets/js/cameraViewRunner.min.js.map
  views/assets/js/currentOperationsViewRunner.min.js
  views/assets/js/currentOperationsViewRunner.min.js.map
  views/assets/js/dashboardRunner.min.js
  views/assets/js/dashboardRunner.min.js.map
  views/assets/js/filamentManagement.min.js
  views/assets/js/filamentManagement.min.js.map
  views/assets/js/fileManagerRunner.min.js
  views/assets/js/fileManagerRunner.min.js.map
  views/assets/js/historyRunner.min.js
  views/assets/js/historyRunner.min.js.map
  views/assets/js/listViewRunner.min.js
  views/assets/js/listViewRunner.min.js.map
  views/assets/js/panelViewRunner.min.js
  views/assets/js/panelViewRunner.min.js.map
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
  views/assets/js/printerMapViewRunner.min.js
  views/assets/js/printerMapViewRunner.min.js.map
  views/assets/js/serverAliveCheck.min.js
  views/assets/js/serverAliveCheck.min.js.map
  views/assets/js/settings.min.js
  views/assets/js/settings.min.js.map
  views/printerManagement.ejs
Labels: effort-20

#419 Job clean refactor
  CHANGELOG.md
  package-lock.json
  package.json
  server_src/lib/dataFunctions/jobClean.js
  server_src/lib/dataFunctions/printerClean.js
  server_src/lib/tests/job-clean.test.js
Labels: chore, effort-5, fixed

#597 Fix deprecated OP API call in state + backwards compat util
  CHANGELOG.md
  package-lock.json
  package.json
  server_src/runners/printerTicker.js
  server_src/runners/state.js
  server_src/utils/compatibility.utils.js
  test/domain-shared/compatibility-util.test.js
Labels: effort-5, fixed

#585 Automatically switch to wss for https printer urls
  CHANGELOG.md
  client_src/js/lib/modules/printerSettings.js
  package-lock.json
  server_2x/src/api/legacy_runners/progress/state.js
  server_src/lib/dataFunctions/printerClean.js
  server_src/models/Printer.js
  server_src/runners/state.js
  server_src/utils/url.utils.js
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
  views/printerManagement.ejs
Labels: effort-10
