Repository OctoFarm/OctoFarm, pull requests merged in 2021-04, with the labels that each got.

#403 Node14 & readme updates
  .github/FUNDING.yml
  .github/workflows/docker_builds.yml
  .github/workflows/docker_builds_alpine.yml
  .github/workflows/docker_builds_monolithic.yml
  .github/workflows/nodejs.yml
  README.md
  docs/USING_DOCKER.md
  package-lock.json
  package.json
Labels: effort-5

#428 Fix readme mongo port and improve non-dev warnings
  README.md
Labels: chore, documentation issue, effort-5

#437 Unrig the explosive skunk left behind by our creator
  views/layout.ejs
Labels: chore

#433 Hotfix remove console log memory system page
  client_src/js/settings.js
  views/assets/js/settings.min.js
  views/assets/js/settings.min.js.map
Labels: chore

#421 Rebased updating OctoFarm + Spectacular log dump
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue-report.md
  .github/ISSUE_TEMPLATE/issue-report.yml
  CHANGELOG.md
  client_src/js/serverAliveCheck.js
  client_src/js/settings.js
  package-lock.json
  package.json
  server_src/config/users.js
  server_src/lib/dataFunctions/printerClean.js
  server_src/lib/logger.js
  server_src/lib/serverCommands.js
  server_src/lib/serverLogs.js
  server_src/lib/serverScripts.js
  server_src/routes/index.js
  server_src/routes/printers.js
  server_src/routes/scripts.js
  server_src/routes/serverChecks.js
  server_src/routes/settings.js
  server_src/runners/scriptCheck.js
  server_src/services/system-information.service.js
  server_src/utils/file.utils.js
  server_src/utils/pretty-print.utils.js
  server_src/utils/system-paths.utils.js
  server_src/utils/zip.utils.js
  test/api/server-check.test.js
  test/api/settings-check.test.js
  test/db-handler.js
  views/assets/css/vendor/slate.css
  views/assets/css/vendor/slate.css.map
  views/assets/js/currentOperationsViewRunner.min.js
  views/assets/js/currentOperationsViewRunner.min.js.map
  views/assets/js/dashboardRunner.min.js
  views/assets/js/dashboardRunner.min.js.map
  views/assets/js/filamentManagement.min.js
  views/assets/js/filamentManagement.min.js.map
  views/assets/js/fileManagerRunner.min.js
  views/assets/js/fileManagerRunner.min.js.map
  views/assets/js/historyRunner.min.js
  views/assets/js/historyRunner.min.js.map
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
  views/assets/js/printerMapViewRunner.min.js
  views/assets/js/printerMapViewRunner.min.js.map
  views/assets/js/serverAliveCheck.min.js
  views/assets/js/serverAliveCheck.min.js.map
  views/assets/js/settings.min.js
  views/assets/js/settings.min.js.map
  views/assets/js/workers/dashboardWorker.min.js
  views/assets/js/workers/dashboardWorker.min.js.map
  views/assets/js/workers/monitoringViewsWorker.min.js
  views/assets/js/workers/monitoringViewsWorker.min.js.map
  views/assets/js/workers/printersManagerWorker.min.js
  views/assets/js/workers/printersManagerWorker.min.js.map
  views/system.ejs
Labels: effort-10

#443 441 update nodejs dockers
  alpine.Dockerfile
  monolithic.Dockerfile
Labels: effort-5, fixed

#435 Env config, improve database error fallback and .env migration
  .gitignore
  alpine.Dockerfile
  app-core.js
  app-env.js
  app-test.js
  app.js
  client_src/js/lib/modules/viewUpdater.js
  config/db.js
  docker/alpine-entrypoint.sh
  docker/entrypoint.sh
  docker/monolithic-entrypoint.sh
  docs/ENVIRONMENT_SETUP.md
  package-lock.json
  package.json
  server_src/config/passport.js
  server_src/lib/dataFunctions/historyClean.js
  server_src/lib/dataFunctions/printerClean.js
  server_src/lib/influxExport.js
  server_src/lib/logger.js
  server_src/routes/databaseIssue.js
  server_src/routes/index.js
  server_src/routes/serverChecks.js
  server_src/runners/autoDiscovery.js
  server_src/settings/serverSettings.js
  server_src/utils/env.utils.js
  test/api/database-issues.test.js
  test/api/mock-data/package.json
  test/api/server-check.test.js
  views/database.ejs
  views/databaseIssue.ejs
Labels: effort-5, fixed, onhold

#453 Fix env, fix variables and safety checks for pm2/nodemon/docker modes
  app-core.js
  app-env.js
  app-test.js
  app.js
  server_src/app.constants.js
  server_src/lib/logger.js
  server_src/routes/databaseIssue.js
  server_src/routes/index.js
  server_src/settings/serverSettings.js
  server_src/utils/env.utils.js
  test/api/settings-check.test.js
  views/databaseIssue.ejs
  views/system.ejs
Labels: bug, effort-5, fixed

#446 Fixed #438 - Moved toFixed() function inside the generateBytes functi…
  CHANGELOG.md
  views/partials/FileManager/fileManagerStatistics.ejs
  views/partials/functions/pretty.js
Labels: fixed

#451 bring back old issue report with updated note about new log dump
  .github/ISSUE_TEMPLATE/developer-task.md
  .github/ISSUE_TEMPLATE/issue-report.md
Labels: fixed

#447 Attempted fix for #439
  CHANGELOG.md
  client_src/js/lib/modules/viewUpdater.js
  views/assets/js/cameraViewRunner.min.js
  views/assets/js/cameraViewRunner.min.js.map
  views/assets/js/listViewRunner.min.js
  views/assets/js/listViewRunner.min.js.map
  views/assets/js/panelViewRunner.min.js
  views/assets/js/panelViewRunner.min.js.map
Labels: fixed

#445 Feature/444+442 updater improvements
  CHANGELOG.md
  client_src/js/settings.js
  server_src/lib/serverCommands.js
  server_src/routes/settings.js
  server_src/utils/npm.utils.js
  views/assets/js/settings.min.js
  views/assets/js/settings.min.js.map
  views/system.ejs
Labels: fixed

#449 Bugfix/history patchwork
  CHANGELOG.md
  server_src/runners/history.js
  server_src/utils/__mocks__/download.util.js
  server_src/utils/download.util.js
  test/application/history-runner.test.js
  test/domain-shared/download-from-octoprint-util.test.js
Labels: fixed

#464 npm update lock file
  package-lock.json
Labels: chore

#469 Hotfix/465 GitHub update runner
  server_src/lib/logger.js
  server_src/runners/githubClient.js
  server_src/runners/softwareUpdateChecker.js
  views/assets/js/cameraViewRunner.min.js
  views/assets/js/cameraViewRunner.min.js.map
  views/assets/js/fileManagerRunner.min.js
  views/assets/js/fileManagerRunner.min.js.map
  views/assets/js/listViewRunner.min.js
  views/assets/js/listViewRunner.min.js.map
  views/assets/js/panelViewRunner.min.js
  views/assets/js/panelViewRunner.min.js.map
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
  views/assets/js/printerMapViewRunner.min.js
  views/assets/js/printerMapViewRunner.min.js.map
Labels: bug, chore, effort-5, fixed

#476 Fixed #459 - Duplicate Id's on printer manager page
  client_src/js/printerManagementRunner.js
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
Labels: bug, effort-5, fixed

#486 Remove prerelease filter as it would not work like this
  docs/ENVIRONMENT_SETUP.md
  server_src/app.constants.js
  server_src/routes/index.js
Labels: bug, effort-5

#485 Feature/296 allow editing site title
  CHANGELOG.md
  app-env.js
  docs/ENVIRONMENT_SETUP.md
  server_src/app.constants.js
  server_src/routes/databaseIssue.js
  server_src/routes/index.js
  server_src/routes/users.js
  views/layout.ejs
Labels: feature request, patreon

#477 Bugfix/settings improvement cache
  server_src/models/ServerSettings.js
Labels: effort-5, fixed

#493 Development release 1.1.13
  .github/ISSUE_TEMPLATE/developer-task.md
  .github/ISSUE_TEMPLATE/issue-report.md
  CHANGELOG.md
  app-env.js
  app.js
  client_src/js/printerManagementRunner.js
  client_src/js/serverAliveCheck.js
  client_src/js/settings.js
  docker/entrypoint.sh
  docker/monolithic-entrypoint.sh
  docs/ENVIRONMENT_SETUP.md
  ecosystem.config.js
  package-lock.json
  package.json
  server_src/app.constants.js
  server_src/lib/logger.js
  server_src/lib/serverCommands.js
  server_src/models/ServerSettings.js
  server_src/routes/databaseIssue.js
  server_src/routes/index.js
  server_src/routes/settings.js
  server_src/routes/users.js
  server_src/runners/githubClient.js
  server_src/runners/softwareUpdateChecker.js
  server_src/runners/systemInfo.js
  test-node12.Dockerfile
  test/application/system-info-runner.test.js
  views/assets/js/cameraViewRunner.min.js
  views/assets/js/cameraViewRunner.min.js.map
  views/assets/js/fileManagerRunner.min.js
  views/assets/js/fileManagerRunner.min.js.map
  views/assets/js/listViewRunner.min.js
  views/assets/js/listViewRunner.min.js.map
  views/assets/js/panelViewRunner.min.js
  views/assets/js/panelViewRunner.min.js.map
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
  views/assets/js/printerMapViewRunner.min.js
  views/assets/js/printerMapViewRunner.min.js.map
  views/assets/js/serverAliveCheck.min.js
  views/assets/js/serverAliveCheck.min.js.map
  views/assets/js/settings.min.js
  views/assets/js/settings.min.js.map
  views/layout.ejs
  views/system.ejs
Labels: effort-10, fixed, needs-discussion-topic, onhold, patreon, question, stale

#508 simple-git scenario tests
  server_src/lib/serverCommands.js
  server_src/utils/__mocks__/npm.utils.js
  server_src/utils/git.utils.js
  test/application/__mocks__/simple-git.js
  test/application/server-commands.test.js
Labels: chore, effort-5

#502 Fixed #501 - Added a check if command exists and timeout in restart command
  package-lock.json
  package.json
  server_src/lib/serverCommands.js
  server_src/utils/system-paths.utils.js
  test/application/server-commands.test.js
Labels: bug, fixed
