Repository OctoFarm/OctoFarm, pull requests merged in 2021-03, with the labels that each got.

#355 Fixed #354 - Printer import didn't load correct table
  client_src/js/printerManagementRunner.js
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
Labels: fixed

#370 Should not expose udp but tcp - monolithic container
  monolithic.Dockerfile
Labels: bug

#384 GitHub tag workflow for automatic prerelease (incl gulp build and assets)
  .gitattributes
  .github/workflows/tag_auto_prerelease.yml
  .github/workflows_disabled/gulp_push.yml
  .gitignore
  .idea/OctoFarm.iml
  .idea/dictionaries/s1mpleman.xml
  .idea/jsLibraryMappings.xml
  .idea/mongoSettings.xml
  package-lock.json
  package.json
  views/assets/css/octofarm.css
  views/images/noCamera.jpg
  views/images/userAPIKEYOctoPrint.png
  views/images/userApplicationKeyOctoPrint.png
  views/images/userCORSOctoPrint.png
  views/images/userSettingsOctoPrint.png
Labels: effort-5

#390 Bugfix/filament manager cleanup
  client_src/js/filamentManagement.js
  views/assets/js/filamentManagement.min.js
  views/assets/js/filamentManagement.min.js.map
  views/filament.ejs
Labels: effort-20

#392 Bugfix/incorrect print progress
  client_src/js/lib/modules/viewUpdater.js
  server_src/lib/dataFunctions/jobClean.js
  views/assets/js/cameraViewRunner.min.js
  views/assets/js/cameraViewRunner.min.js.map
  views/assets/js/listViewRunner.min.js
  views/assets/js/listViewRunner.min.js.map
  views/assets/js/panelViewRunner.min.js
  views/assets/js/panelViewRunner.min.js.map
  views/images/noCamera.jpg
  views/images/userAPIKEYOctoPrint.png
  views/images/userApplicationKeyOctoPrint.png
  views/images/userCORSOctoPrint.png
  views/images/userSettingsOctoPrint.png
Labels: effort-5

#399 Fixed #398 - Power settings disappeared
  CHANGELOG.md
  client_src/js/lib/modules/printerSettings.js
  views/assets/js/printerManagementRunner.min.js
  views/assets/js/printerManagementRunner.min.js.map
Labels: bug, fixed
